[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sb_coinflip = "9WZbqYGMxAfaybk5m56J6yuYUW1ryyguSvJEtA884t8o"

[programs.devnet]
sb_coinflip = "9WZbqYGMxAfaybk5m56J6yuYUW1ryyguSvJEtA884t8o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aster27/Desktop/dev_creds/DevXPxYms5t88gQQ5w9N8z5ifu8F6F8KPKYjaYRrkQei.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
